org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.140
neo_version_range=[21.1,)
loader_version_range=[4,)

# Parchment
parchment_mappings_version=2024.11.17
parchment_minecraft_version=1.21.1

# Mod
mod_id=scountry
mod_name=SCountry
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.bensonskiy.scountry
mod_authors=bensonskiy
mod_description=SCountry — мод для Minecraft 1.21.1 на NeoForge.